// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bilibili.dart';
import 'api/bilibili/bilibili.dart';
import 'api/data.dart';
import 'api/data/bilibili.dart';
import 'api/log.dart';
import 'api/lyric.dart';
import 'api/msg_center.dart';
import 'api/util.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SenderProgressDataPtr => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Client
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          dynamic raw);

  @protected
  SenderProgressData
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          dynamic raw);

  @protected
  Client
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          dynamic raw);

  @protected
  Client
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          dynamic raw);

  @protected
  SenderProgressData
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          dynamic raw);

  @protected
  RustStreamSink<MsgItem> dco_decode_StreamSink_msg_item_Sse(dynamic raw);

  @protected
  RustStreamSink<ProgressData> dco_decode_StreamSink_progress_data_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Audio dco_decode_audio(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SenderProgressData
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          dynamic raw);

  @protected
  MsgItem dco_decode_box_autoadd_msg_item(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VideoQuality dco_decode_box_autoadd_video_quality(dynamic raw);

  @protected
  BvInfo dco_decode_bv_info(dynamic raw);

  @protected
  Dash dco_decode_dash(dynamic raw);

  @protected
  DescV2 dco_decode_desc_v_2(dynamic raw);

  @protected
  Dimension dco_decode_dimension(dynamic raw);

  @protected
  Durl dco_decode_durl(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InfoData dco_decode_info_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Audio> dco_decode_list_audio(dynamic raw);

  @protected
  List<DescV2> dco_decode_list_desc_v_2(dynamic raw);

  @protected
  List<Durl> dco_decode_list_durl(dynamic raw);

  @protected
  List<Page> dco_decode_list_page(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchLyricItem> dco_decode_list_search_lyric_item(dynamic raw);

  @protected
  List<SupportFormat> dco_decode_list_support_format(dynamic raw);

  @protected
  List<Video> dco_decode_list_video(dynamic raw);

  @protected
  MsgItem dco_decode_msg_item(dynamic raw);

  @protected
  MsgType dco_decode_msg_type(dynamic raw);

  @protected
  SenderProgressData?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Owner dco_decode_owner(dynamic raw);

  @protected
  Page dco_decode_page(dynamic raw);

  @protected
  ProgressData dco_decode_progress_data(dynamic raw);

  @protected
  Rights dco_decode_rights(dynamic raw);

  @protected
  SearchLyricItem dco_decode_search_lyric_item(dynamic raw);

  @protected
  SegmentBase dco_decode_segment_base(dynamic raw);

  @protected
  Stat dco_decode_stat(dynamic raw);

  @protected
  SupportFormat dco_decode_support_format(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Video dco_decode_video(dynamic raw);

  @protected
  VideoQuality dco_decode_video_quality(dynamic raw);

  @protected
  VideoUrl dco_decode_video_url(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Client
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          SseDeserializer deserializer);

  @protected
  SenderProgressData
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SseDeserializer deserializer);

  @protected
  Client
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          SseDeserializer deserializer);

  @protected
  Client
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          SseDeserializer deserializer);

  @protected
  SenderProgressData
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<MsgItem> sse_decode_StreamSink_msg_item_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ProgressData> sse_decode_StreamSink_progress_data_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Audio sse_decode_audio(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SenderProgressData
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SseDeserializer deserializer);

  @protected
  MsgItem sse_decode_box_autoadd_msg_item(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VideoQuality sse_decode_box_autoadd_video_quality(
      SseDeserializer deserializer);

  @protected
  BvInfo sse_decode_bv_info(SseDeserializer deserializer);

  @protected
  Dash sse_decode_dash(SseDeserializer deserializer);

  @protected
  DescV2 sse_decode_desc_v_2(SseDeserializer deserializer);

  @protected
  Dimension sse_decode_dimension(SseDeserializer deserializer);

  @protected
  Durl sse_decode_durl(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InfoData sse_decode_info_data(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Audio> sse_decode_list_audio(SseDeserializer deserializer);

  @protected
  List<DescV2> sse_decode_list_desc_v_2(SseDeserializer deserializer);

  @protected
  List<Durl> sse_decode_list_durl(SseDeserializer deserializer);

  @protected
  List<Page> sse_decode_list_page(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchLyricItem> sse_decode_list_search_lyric_item(
      SseDeserializer deserializer);

  @protected
  List<SupportFormat> sse_decode_list_support_format(
      SseDeserializer deserializer);

  @protected
  List<Video> sse_decode_list_video(SseDeserializer deserializer);

  @protected
  MsgItem sse_decode_msg_item(SseDeserializer deserializer);

  @protected
  MsgType sse_decode_msg_type(SseDeserializer deserializer);

  @protected
  SenderProgressData?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Owner sse_decode_owner(SseDeserializer deserializer);

  @protected
  Page sse_decode_page(SseDeserializer deserializer);

  @protected
  ProgressData sse_decode_progress_data(SseDeserializer deserializer);

  @protected
  Rights sse_decode_rights(SseDeserializer deserializer);

  @protected
  SearchLyricItem sse_decode_search_lyric_item(SseDeserializer deserializer);

  @protected
  SegmentBase sse_decode_segment_base(SseDeserializer deserializer);

  @protected
  Stat sse_decode_stat(SseDeserializer deserializer);

  @protected
  SupportFormat sse_decode_support_format(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Video sse_decode_video(SseDeserializer deserializer);

  @protected
  VideoQuality sse_decode_video_quality(SseDeserializer deserializer);

  @protected
  VideoUrl sse_decode_video_url(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SenderProgressData self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          Client self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SenderProgressData self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_msg_item_Sse(
      RustStreamSink<MsgItem> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_progress_data_Sse(
      RustStreamSink<ProgressData> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio(Audio self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SenderProgressData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_msg_item(MsgItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_quality(
      VideoQuality self, SseSerializer serializer);

  @protected
  void sse_encode_bv_info(BvInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dash(Dash self, SseSerializer serializer);

  @protected
  void sse_encode_desc_v_2(DescV2 self, SseSerializer serializer);

  @protected
  void sse_encode_dimension(Dimension self, SseSerializer serializer);

  @protected
  void sse_encode_durl(Durl self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_info_data(InfoData self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio(List<Audio> self, SseSerializer serializer);

  @protected
  void sse_encode_list_desc_v_2(List<DescV2> self, SseSerializer serializer);

  @protected
  void sse_encode_list_durl(List<Durl> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page(List<Page> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_search_lyric_item(
      List<SearchLyricItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_support_format(
      List<SupportFormat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_video(List<Video> self, SseSerializer serializer);

  @protected
  void sse_encode_msg_item(MsgItem self, SseSerializer serializer);

  @protected
  void sse_encode_msg_type(MsgType self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          SenderProgressData? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_owner(Owner self, SseSerializer serializer);

  @protected
  void sse_encode_page(Page self, SseSerializer serializer);

  @protected
  void sse_encode_progress_data(ProgressData self, SseSerializer serializer);

  @protected
  void sse_encode_rights(Rights self, SseSerializer serializer);

  @protected
  void sse_encode_search_lyric_item(
      SearchLyricItem self, SseSerializer serializer);

  @protected
  void sse_encode_segment_base(SegmentBase self, SseSerializer serializer);

  @protected
  void sse_encode_stat(Stat self, SseSerializer serializer);

  @protected
  void sse_encode_support_format(SupportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video(Video self, SseSerializer serializer);

  @protected
  void sse_encode_video_quality(VideoQuality self, SseSerializer serializer);

  @protected
  void sse_encode_video_url(VideoUrl self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
              ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
          int ptr);

  external void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderProgressData(
          int ptr);
}
