// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data/bilibili.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `content_length`, `from_str`, `request_api`, `request_web`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {
  Future<List<String>> audioUrls(
      {required String bvid, required PlatformInt64 cid});

  Future<void> download(
      {required String url,
      required String filePath,
      SenderProgressData? channel});

  Future<List<String>> fetchIds(
      {required String keyword, required BigInt maxIdCount});

  Future<BvInfo> info({required String bvid});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Client> newInstance() =>
      RustLib.instance.api.crateApiBilibiliBilibiliClientNew();

  Future<VideoUrl> videoUrl(
      {required String bvid,
      required PlatformInt64 cid,
      required PlatformInt64 fnval,
      required VideoQuality videoQuality});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Sender < ProgressData >>>
abstract class SenderProgressData implements RustOpaqueInterface {}
