[package]
name = "rust_lib_musicbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
log = "0.4"
anyhow = "1.0"
chrono = "0.4"
flutter_rust_bridge = "=2.0.0-dev.33"
tokio = { version = "1", features = ["full"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"

# desktop platform
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
reqwest = { version = "0.12", features = ["json", "socks"] }

# mobile platform
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
reqwest = { version = "0.12", features = [
  "rustls-tls",
  "native-tls-vendored",
  "json",
  "socks",
] }


