// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> bvFetchIds(
        {required String keyword, required BigInt maxIdCount}) =>
    RustLib.instance.api
        .crateApiBilibiliBvFetchIds(keyword: keyword, maxIdCount: maxIdCount);

Future<InfoData> bvVideoInfo({required String bvid}) =>
    RustLib.instance.api.crateApiBilibiliBvVideoInfo(bvid: bvid);

Stream<ProgressData> bvDownloadVideoByIdWithCallback(
        {required String id,
        required PlatformInt64 cid,
        required String downloadPath}) =>
    RustLib.instance.api.crateApiBilibiliBvDownloadVideoByIdWithCallback(
        id: id, cid: cid, downloadPath: downloadPath);

String bvWatchUrl({required String id}) =>
    RustLib.instance.api.crateApiBilibiliBvWatchUrl(id: id);
