// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> bvFetchIds(
        {required String keyword,
        required int maxIdCount,
        String? proxyUrl,
        dynamic hint}) =>
    RustLib.instance.api.bvFetchIds(
        keyword: keyword,
        maxIdCount: maxIdCount,
        proxyUrl: proxyUrl,
        hint: hint);

Future<InfoData> bvVideoInfo(
        {required String bvid, String? proxyUrl, dynamic hint}) =>
    RustLib.instance.api
        .bvVideoInfo(bvid: bvid, proxyUrl: proxyUrl, hint: hint);

Stream<ProgressData> bvDownloadVideoByIdWithCallback(
        {required String id,
        required int cid,
        required String downloadPath,
        String? proxyUrl,
        dynamic hint}) =>
    RustLib.instance.api.bvDownloadVideoByIdWithCallback(
        id: id,
        cid: cid,
        downloadPath: downloadPath,
        proxyUrl: proxyUrl,
        hint: hint);

String bvWatchUrl({required String id, dynamic hint}) =>
    RustLib.instance.api.bvWatchUrl(id: id, hint: hint);
