// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> bvFetchIds(
        {required String keyword,
        required BigInt maxIdCount,
        String? proxyUrl}) =>
    RustLib.instance.api.crateApiBilibiliBvFetchIds(
        keyword: keyword, maxIdCount: maxIdCount, proxyUrl: proxyUrl);

Future<InfoData> bvVideoInfo({required String bvid, String? proxyUrl}) =>
    RustLib.instance.api
        .crateApiBilibiliBvVideoInfo(bvid: bvid, proxyUrl: proxyUrl);

Stream<ProgressData> bvDownloadVideoByIdWithCallback(
        {required String id,
        required PlatformInt64 cid,
        required String downloadPath,
        String? proxyUrl}) =>
    RustLib.instance.api.crateApiBilibiliBvDownloadVideoByIdWithCallback(
        id: id, cid: cid, downloadPath: downloadPath, proxyUrl: proxyUrl);

String bvWatchUrl({required String id}) =>
    RustLib.instance.api.crateApiBilibiliBvWatchUrl(id: id);
