// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class InfoData {
  final String title;
  final String author;
  final String videoId;
  final String shortDescription;
  final int viewCount;
  final int lengthSeconds;

  const InfoData({
    required this.title,
    required this.author,
    required this.videoId,
    required this.shortDescription,
    required this.viewCount,
    required this.lengthSeconds,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      videoId.hashCode ^
      shortDescription.hashCode ^
      viewCount.hashCode ^
      lengthSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InfoData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          videoId == other.videoId &&
          shortDescription == other.shortDescription &&
          viewCount == other.viewCount &&
          lengthSeconds == other.lengthSeconds;
}

class ProgressData {
  final int currentSize;
  final int? totalSize;

  const ProgressData({
    required this.currentSize,
    this.totalSize,
  });

  @override
  int get hashCode => currentSize.hashCode ^ totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressData &&
          runtimeType == other.runtimeType &&
          currentSize == other.currentSize &&
          totalSize == other.totalSize;
}
