// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `ComEntry` is not used by any `pub` functions, thus it is ignored.
// The type `POOL` is not used by any `pub` functions, thus it is ignored.

Future<void> createDb({required String dbPath, dynamic hint}) =>
    RustLib.instance.api.createDb(dbPath: dbPath, hint: hint);

Future<void> deleteDb({required String dbPath, dynamic hint}) =>
    RustLib.instance.api.deleteDb(dbPath: dbPath, hint: hint);

Future<void> closeDb({dynamic hint}) =>
    RustLib.instance.api.closeDb(hint: hint);

Future<void> createTable({required String sql, dynamic hint}) =>
    RustLib.instance.api.createTable(sql: sql, hint: hint);

Future<void> insert({required String sql, dynamic hint}) =>
    RustLib.instance.api.insert(sql: sql, hint: hint);

Future<void> update({required String sql, dynamic hint}) =>
    RustLib.instance.api.update(sql: sql, hint: hint);

Future<void> delete({required String sql, dynamic hint}) =>
    RustLib.instance.api.delete(sql: sql, hint: hint);

Future<void> deleteAll({required String sql, dynamic hint}) =>
    RustLib.instance.api.deleteAll(sql: sql, hint: hint);

Future<List<Map<String, String>>> select({required String sql, dynamic hint}) =>
    RustLib.instance.api.select(sql: sql, hint: hint);

Future<List<Map<String, String>>> selectAll(
        {required String sql, dynamic hint}) =>
    RustLib.instance.api.selectAll(sql: sql, hint: hint);

Future<void> dropTable({required String sql, dynamic hint}) =>
    RustLib.instance.api.dropTable(sql: sql, hint: hint);

Future<int> rowCount({required String sql, dynamic hint}) =>
    RustLib.instance.api.rowCount(sql: sql, hint: hint);
