// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_lyrics`, `get_author_and_token`, `headers`, `inner_search`, `lyric_html`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<SearchLyricItem>> searchLyric({required String keyword}) =>
    RustLib.instance.api.crateApiLyricSearchLyric(keyword: keyword);

Future<String> getLyric({required String token}) =>
    RustLib.instance.api.crateApiLyricGetLyric(token: token);

Future<void> saveLyric({required String text, required String path}) =>
    RustLib.instance.api.crateApiLyricSaveLyric(text: text, path: path);

class SearchLyricItem {
  final String name;
  final String authors;
  final String token;

  const SearchLyricItem({
    required this.name,
    required this.authors,
    required this.token,
  });

  static Future<SearchLyricItem> default_() =>
      RustLib.instance.api.crateApiLyricSearchLyricItemDefault();

  @override
  int get hashCode => name.hashCode ^ authors.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchLyricItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          authors == other.authors &&
          token == other.token;
}
