// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.33.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<SearchLyricItem>> searchLyric(
        {required String keyword, dynamic hint}) =>
    RustLib.instance.api.searchLyric(keyword: keyword, hint: hint);

Future<String> getLyric({required String token, dynamic hint}) =>
    RustLib.instance.api.getLyric(token: token, hint: hint);

Future<void> saveLyric(
        {required String text, required String path, dynamic hint}) =>
    RustLib.instance.api.saveLyric(text: text, path: path, hint: hint);

class SearchLyricItem {
  final String name;
  final String authors;
  final String token;

  const SearchLyricItem({
    required this.name,
    required this.authors,
    required this.token,
  });

  @override
  int get hashCode => name.hashCode ^ authors.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchLyricItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          authors == other.authors &&
          token == other.token;
}
